name: lost

volumes:
  app:
  data:
  db:

services:
  traefik:
    image: traefik:3.4.0
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik.log:/traefik.log
    restart: always

  frontend:
    image: l3pcv/lost-frontend:${LOST_VERSION}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.lost-frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.lost-frontend.entrypoints=web

  backend:
    image: l3pcv/lost-backend:${LOST_VERSION}
    env_file:
      - .env
    volumes:
      - app:/home/lost/app
      - data:/home/lost/data
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.lost-backend.rule=PathPrefix(`/api`)|| PathPrefix(`/swaggerui`)
      - traefik.http.routers.lost-backend.entrypoints=web
      - traefik.http.routers.lost-backend.service=lost-backend
      - traefik.http.services.lost-backend.loadbalancer.server.port=5000

  db:
    image: mysql:9.3.0
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${LOST_DB_NAME}
      MYSQL_USER: ${LOST_DB_USER}
      MYSQL_PASSWORD: ${LOST_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${LOST_DB_ROOT_PASSWORD}
