- name: Deploy Lost Demo
  hosts: all
  vars:
    overwrite_version: "{{ lookup('env', 'OVERWRITE_VERSION') | default(false) | bool }}"
    image_version: "{{ lookup('env', 'IMAGE_VERSION') }}"
    base_path: "{{ ansible_env.HOME }}/production/lost"

  tasks:
    - name: Copy deployment files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ base_path }}/{{ item }}"
        mode: "0700"
        owner: "1000"
        group: "1000"
      loop:
        - compose.yaml
        - .env

    - name: Set lost docker image tag
      when: overwrite_version
      ansible.builtin.lineinfile:
        path: "{{ (base_path, '.env') | path_join }}"
        regexp: "^LOST_VERSION="
        line: LOST_VERSION={{ image_version }}
        create: true
        mode: "0700"
        owner: "1000"
        group: "1000"

    - name: Start docker compose up
      community.docker.docker_compose_v2:
        project_src: "{{ base_path }}"
        state: present
