- name: Deploy Lost Demo
  hosts: all
  vars:
    overwrite_version: "{{ lookup('env', 'OVERWRITE_VERSION') | default(false) | bool }}"
    image_version: "{{ lookup('env', 'IMAGE_VERSION') }}"
    base_path: "{{ ansible_env.HOME }}/production/lost"

  tasks:
    - name: Create app directory
      ansible.builtin.file:
        path: "{{ base_path }}"
        state: directory
        mode: "0700"
        owner: "1000"
        group: "1000"

    - name: Create empty traefik log file
      ansible.builtin.file:
        path: "{{ base_path }}/traefik.log"
        state: touch
        mode: "0700"
        owner: "1000"
        group: "1000"

    - name: Copy deployment files
      ansible.builtin.copy:
        src: "../lost/{{ item }}"
        dest: "{{ base_path }}/{{ item }}"
        mode: "0700"
        owner: "1000"
        group: "1000"
      loop:
        - .env
        - compose.yaml
        - traefik.yaml

    - name: Start docker compose up
      community.docker.docker_compose_v2:
        project_src: "{{ base_path }}"
        state: present
