all:
  hosts:
    lostserver:
      ansible_host: "{{ lookup('file', '../values/floating_ip/floating_ip.txt') | trim }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ./values/ssh_keys/generated_private_key.pem
